### ISSUE TITLE
Add new `create_output_type_sample()` to handle new v3.0.0 schema specification

### ISSUE THREAD

**Issue by annakrystalli** [hubverse-org/hubAdmin#18]
The current `create_output_type_sample()` function are based on expectations that a sample output type will contain an `output_type_id` object of `required` and `optional` vectors of values.

The new function needs to create an `output_type_id_params` object instead of an `output_type_id` object with the properties described in v3.0.0 of the schema.

This consists of a breaking change. 

Should we allow back compatibility with earlier schema versions or should we just make a breaking change and notify any users trying to create sample output type ids using earlier schema versions that we only support schema =< 3.0.0 going forward?

**Comment by elray1** [comment]
I vote for just making a breaking change here.  Any old support for samples was really in a kind of "alpha" status.

**Comment by annakrystalli** [comment]
Great! I was going to ask this as a broader question in a Discussion as functionality in `hubValidations` and utilities in `hubData` like `hubData::expand_model_out_val_grid()` will also be affected. Can I take this answer to apply throught the hubverse?

**Comment by LucieContamin** [comment]
I am ok with making a breaking change. We are using a slightly different format already, based on Hubverse but adapted for SMH.

**Comment by nickreich** [comment]
@annakrystalli when you ask

> Can I take this answer to apply throught the hubverse?

Do you mean, is it ok if we update functions so that they would break for anyone using older sample formats? I think the question is "yes". Maybe we can/should send out a warning on the announcements email list. I don't think anyone is using this functionality, so I'm not even sure we should consider it "breaking" functionality for, say, the purposes of semantic versioning.

**Comment by annakrystalli** [comment]
Yes! Sorry for the vagueness. My idea was to throw a simple error if sample definitions prior to v3.0.0 and point to the new schema. But a quick notification via email is also a good idea. Let me also briefly mention it tomorrow on the community call.
