### ISSUE TITLE
use an option for schema version for create functions

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubAdmin#85]
In [reichlab/variant-nowcast-hub#176](https://github.com/reichlab/variant-nowcast-hub/pull/176/files#diff-3361d89a46e263279543b41cee56a8c99852d1f2052dd4bfe295d54842d57fdb), the workflow to create a new round began to fail because the default schema for functions like `create_task_id` is "latest" so it constructed a v4 schema instead of v3.0.1 resulting in the following error:

```
ℹ Existing config found, adding a new round
Error in `hubAdmin::append_round()`:
✖ Schema version mismatch between `config` and round.
! Must be the same.
• `config`:
  "https://raw.githubusercontent.com/hubverse-org/schemas/main/v3.0.1/tasks-schema.json"
• round:
  "https://raw.githubusercontent.com/hubverse-org/schemas/main/v4.0.0/tasks-schema.json"
Backtrace:
    ▆
 1. └─hubAdmin::append_round(existing_task_config, new_round)
 2.   └─cli::cli_abort(...) at hubAdmin/R/append_round.R:133:5
 3.     └─rlang::abort(...)
```

I think we should specify `schema = getOption("hubAdmin.schema_version", default = "latest")` in the function signatures, so that way users can specify one line at the top of their script to set the schema version while they are developing the script. 

```r
options(hubAdmin.schema_version = "v3.0.1")
```

**Comment by annakrystalli** [comment]
This is a great idea! Will implement!

**Comment by annakrystalli** [comment]
Will also include an option for `branch`
